### ISSUE TITLE
In AutoQuerable 1.4 ICollection is always null after AutoQueryable is called.

### ISSUE THREAD

**Issue by jnUser** [trenoncourt/AutoQueryable#32]
I have query that returns object with string array. After projection when I call autoquerable the array is always null. There is data in autoquerable version 1.1 but not in 1.4. 

The short version of the code:

var result =
dbContext.Foo
.FromSql(GetSql())
Select( a => new DO
{
  id = a.id
  names = a.names.Split(new[] { ", " }, StringSplitOptions.RemoveEmptyEntries),
});

IQueryable<object> queryResult = result
          .ProjectTo<TReturnDTO>()
         .AutoQueryable(queryString, new AutoQueryableProfile { UseBaseType = true });

 return await queryResult.ToListAsync();

In queryResult ICollection names is always null even if the result has names. It works in version 1.1

I am using Core 2.0 and AutoQuerable 1.4.

**Comment by trenoncourt** [comment]
Hi @jnUser ,

do you have the same problem with UseBaseType = false ?

**Comment by jnUser** [comment]
Thank you for the speedy reply. With UseBaseType = false the names is missing from the Json so I think it is still null. In the result the string array names has values or is an empty array.

**Comment by trenoncourt** [comment]
Could you give me your queryString and you model ? I will try to reproduce

**Comment by jnUser** [comment]
I made a simple test project to reproduce the issue in smaller scale. I can email it to you if it helps.

querySting: "?take=250"
model:
    public class BloggingContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=EFGetStarted.ConsoleApp.NewDb;Trusted_Connection=True;");
        }
    }

    public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }

        public List<Post> Posts { get; set; }
    }

    public class Post
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }

        public int BlogId { get; set; }
        public Blog Blog { get; set; }
    }

I am quering a DTO that has BlogId and ICollection of Posts Contents.

**Comment by trenoncourt** [comment]
relationships are not fetched by default.
If you want the relationships back, you have to specify them in the select clause:
```select=posts```
The problem is that you have to add all the other fields you need:
```select=blogid,url,posts```
Let's say you need to recover the relationships in posts you can do it like that:
```select=blogid,url,posts.*```

I'm going to add 2 features pretty quickly:
The ability to retrieve all relationships from level 0 via ```select=*```.
The possibility to retrieve all the fields of level 0 without relationships, it will allow to write requests of this kind: ```select=_,posts```
