### ISSUE TITLE
Escaping the comma separator

### ISSUE THREAD

**Issue by jpraes** [trenoncourt/AutoQueryable#37]
So, my scenario is that I am requesting for all items that contain certain text but in this case the text often includes a comma. But the comma is used as an OR operator in the filters, so that causes problems. 

For example: 

We have a list of employees that have a field employeeName that is of type "00, Firstname Lastname". 

If we do a search "/employees?employeeNameContains=11, Fred", this wouldn't return every employee that has a code 11 and Fred as their first name. 

I would like to know if there is already a way to get around this problem, or if isn't, could it be done?

**Comment by trenoncourt** [comment]
Hi,
If you want to use AND instead of OR you can make requests like that :
```
http://localhost:5000/api/products?top=50&select=name&nameContains=Product&nameContains=1
``` 
you'll get result like that:
```
[{"name":"Product 1"},{"name":"Product 10"},{"name":"Product 11"},{"name":"Product 12"},{"name":"Product 13"},{"name":"Product 14"},{"name":"Product 15"},{"name":"Product 16"},{"name":"Product 17"},{"name":"Product 18"},{"name":"Product 19"},{"name":"Product 21"},{"name":"Product 31"},{"name":"Product 41"},{"name":"Product 51"},{"name":"Product 61"},{"name":"Product 71"},{"name":"Product 81"},{"name":"Product 91"},{"name":"Product 100"},{"name":"Product 101"},{"name":"Product 102"},{"name":"Product 103"},{"name":"Product 104"},{"name":"Product 105"},{"name":"Product 106"},{"name":"Product 107"},{"name":"Product 108"},{"name":"Product 109"},{"name":"Product 110"},{"name":"Product 111"},{"name":"Product 112"},{"name":"Product 113"},{"name":"Product 114"},{"name":"Product 115"},{"name":"Product 116"},{"name":"Product 117"},{"name":"Product 118"},{"name":"Product 119"},{"name":"Product 120"},{"name":"Product 121"},{"name":"Product 122"},{"name":"Product 123"},{"name":"Product 124"},{"name":"Product 125"},{"name":"Product 126"},{"name":"Product 127"},{"name":"Product 128"},{"name":"Product 129"},{"name":"Product 130"}]
```
I'm working on a better filter feature to make subfilters easyly

**Comment by jpraes** [comment]
I'll give it a shot, it requires little tweaks to the search terms since this is implemented on a search box tool.

Like so,

1. user types "Product" to the search box

--> request made: /api/products?nameContains=Product

2. updates the search term to "Produ"

--> request: /api/products?nameContains=Produ 

So now if the search term was "10, Product" the problem occurs. 

But this sounds fitting for my needs, thank you!
