### ISSUE TITLE
UseBaseType not working

### ISSUE THREAD

**Issue by allistoncarlos** [trenoncourt/AutoQueryable#38]
I'm using AutoQueryable on my repository project, trying to decouple it from the API project:

`
public async Task<IQueryable<ProductCategory>> Load(string queryString)
{
            var data = await this.Load();
            var result = data.AsQueryable().AutoQueryable(queryString, new AutoQueryableProfile { UseBaseType = true });
            var transformedData = result as IQueryable<ProductCategory>;
            return transformedData;
 }`

The problem is that the Visual Studio shows returned data in result var, but when I try to cast it to IQueryable<ProductCategory>, it returns null. I'm using MongoDB by the way, encapsulated by my Repository project.

How can I manage to make AutoQueryable work with my project? Does it work only with EF?

Thanks, and congrats for the project!

**Comment by trenoncourt** [comment]
Hi allistoncarlos,

AutoQueryable does not work only with EF, it is working with IQueryable.

Your code seems to be ok.
Can you tell me what is the type of data and if you inspect result are you seeing some data?

Can you tell me too what library are you using to fetch data from Mongo and give me the Load method ?

I will try to reproduce tomorow.

Thanks for using AQ & contributing.

**Comment by allistoncarlos** [comment]
Hi trenoncourt!

Sorry, it was a problem with Mongo Driver. I've updated it, and now it's working perfectly.
For the records, that's my actual Repository.Load method:

`public IQueryable<T> Load(string queryString)
        {
            return collection.AsQueryable().AutoQueryable(queryString, new AutoQueryableProfile { UseBaseType = true }) as IQueryable<T>;
        }`

Thank you so much for the support.
