### ISSUE TITLE
Skip/Take giving an ArgumentNullException

### ISSUE THREAD

**Issue by allistoncarlos** [trenoncourt/AutoQueryable#39]
I'm trying to make Skip/Take work, using a sample query string (?skip=1&take=1). My code was a mess and wasn't working, so I end up running lib source's unit tests.

In the BaseTypeTest.SelectAllProducts I've replaced default query string to the sample above, and got the following exception after running: 

Test method AutoQueryable.UnitTest.BaseTypeTest.SelectAllProducts threw exception: 
System.ArgumentNullException: Value cannot be null.
Parameter name: source
    at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at AutoQueryable.UnitTest.BaseTypeTest.SelectAllProducts() in C:\Projetos\Testes\AutoQueryable-master\test\AutoQueryable.UnitTest\BaseTypeTest.cs:line 22

dbug: Microsoft.EntityFrameworkCore.Infrastructure[100401]
      An 'IServiceProvider' was created for internal use by Entity Framework.
info: Microsoft.EntityFrameworkCore.Infrastructure[100403]
      Entity Framework Core 2.0.0-rtm-26452 initialized 'AutoQueryableContext' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=test 
dbug: Microsoft.EntityFrameworkCore.Query[100101]
      => Microsoft.EntityFrameworkCore.Query.Internal.InMemoryQueryModelVisitor
      Compiling query model: 
      '(from Product <generated>_1 in DbSet<Product>
      select [<generated>_1]).Any()'
dbug: Microsoft.EntityFrameworkCore.Query[100104]
      => Microsoft.EntityFrameworkCore.Query.Internal.InMemoryQueryModelVisitor
      Optimized query model: 
      '(from Product <generated>_1 in DbSet<Product>
      select [<generated>_1]).Any()'
dbug: Microsoft.EntityFrameworkCore.Query[100107]
      => Microsoft.EntityFrameworkCore.Query.Internal.InMemoryQueryModelVisitor
      (QueryContext queryContext) => IEnumerable<bool> _InterceptExceptions(
          source: IEnumerable<bool> _ToSequence(bool Any(IEnumerable<ValueBuffer> ProjectionQuery(
                      queryContext: queryContext, 
                      entityType: EntityType: Product))), 
          contextType: AutoQueryable.UnitTest.Mock.AutoQueryableContext, 
          logger: DiagnosticsLogger<Query>, 
          queryContext: queryContext)
info: Microsoft.EntityFrameworkCore.Update[300100]
      Saved 4006 entities to in-memory store.

PS: using ?top=1 still gives me the same error.

**Comment by trenoncourt** [comment]
hi,
thanks for your contribution, i'll fix that tomorrow ;)
