### ISSUE TITLE
Swagger support

### ISSUE THREAD

**Issue by zeqk** [trenoncourt/AutoQueryable#44]
Can you add support for Swagger documentation?

https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?tabs=visual-studio%2Cvisual-studio-xml

Thanks

**Comment by trenoncourt** [comment]
What kind of doc do you want to add ?

You can use swashbuckle attributes on your controller action.

**Comment by zeqk** [comment]
I mean, If I add the attribute AutoQueryable, let the swagger autogenerate the documentation for the possible queryParams (ex. select, take, etc)

**Comment by trenoncourt** [comment]
Hi zeqk, thanks for this feature.

I will add a package to extend swashbuckle in a future release.
Are you using aspnet core ? (maybe this feature will be for aspnet core only)

**Comment by zeqk** [comment]
Yes, I am using asp.net core. Thank you!

Maybe you can use an IOperationFilter for implement this
