### ISSUE TITLE
request stucks when any exception occurs during query execution

### ISSUE THREAD

**Issue by nurhat** [trenoncourt/AutoQueryable#5]
Hi,
Could you please check following case : 
  -  Use sqlserver(min 2008) for persistency instead of memory persistence provider
  - Donot enable  UseRowNumberForPaging for sql server configuration options. If not enabled then Skip() and Take() wont work
            "x.UseSqlServer(connectionString, b => b.UseRowNumberForPaging())"
  - Try to execute following request => 
             localhost:5000/api/products?take=1&skip=1 
  - The request will stuck 

Best Regards,
Nurhat

**Comment by nurhat** [comment]
Handling exceptions in filter seems to fix the problem.

 
```
  try
            {
                context.Result = new OkObjectResult(QueryableHelper.GetAutoQuery(queryString, entityType, query, new AutoQueryableProfile { UnselectableProperties = UnselectableProperties }));
            }
            catch(Exception ex) {
                context.Result = new BadRequestObjectResult(ex); 
            } 
```

**Comment by trenoncourt** [comment]
Hi nurhat,
Is there a catched exception and what the exception message said ?

It's difficult to me to test with sqlserver 2008 this month (holidays with very small internet connection :)) but i'll test next month if the error persist.
I've tested with version 2012 & 2016 it seems to work.

Best Regards,
Thibaut

**Comment by nurhat** [comment]
Hi,
 The exception is given below. We may ignore it, because to use paging support 
 UseRowNumberForPaging must be enabled unless you are on mssql 2012 or higher .

> System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near 'OFFSET'.
> Invalid usage of the option NEXT in the FETCH statement.
>   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) 
>   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>   .....
