### ISSUE TITLE
DefaultToSelect

### ISSUE THREAD

**Issue by henkosch** [trenoncourt/AutoQueryable#57]
Currently an empty list is returned when select is not specified in the query, because no properties are selected. It would be great to specify a default value for select when select query parameter is not given.

```
[AutoQueryable(DefaultToSelect = "_")]
[AutoQueryable(DefaultToSelect = "*")]
[AutoQueryable(DefaultToSelect = "id,name")]
```

**Comment by trenoncourt** [comment]
Hi @henkosh,

It will be in the next release :).
