### ISSUE TITLE
DisAllowed Clauses

### ISSUE THREAD

**Issue by tomkurian01** [trenoncourt/AutoQueryable#69]
I'm trying to disallow the select clause but it doesn't seem to stop it. When I put this in the query string it still allows it. I'm using the latest pre-release versions V 2.0.4-beta.

http://localhost:11111/api/TruckDeliveryDetail?select=id

```
        [HttpGet, AutoQueryable(DisAllowedClauses = ClauseType.Select)]
        public IQueryable<ObjectDetail> Get()
        {
            return _ctx.ObjectDetail;
        }
```

**Comment by trenoncourt** [comment]
hi @tomkurian01 ,

Thanks for this issue

Fixed in 2.0.5-beta version, with more UT ;).
