### ISSUE TITLE
AutoQueryable with AutoMapper and ASP.Net core

### ISSUE THREAD

**Issue by tomkurian01** [trenoncourt/AutoQueryable#73]
I'm using AutoQueryable along with AutoMapper. And everything is working great until I try to use automapper to send back a DTO back to the client.

So the below code works great:

        [AutoQueryable]
        public IQueryable<DatabaseClassName> Get([FromServices] IQueryableRepository repository)
        {

            return repository.GetIQueryable<DatabaseClassName>();
        }

However this code is not working:

        [AutoQueryable]
        public IQueryable<ViewModel> Get([FromServices] IQueryableRepository repository)
        {

            return repository.GetIQueryable<DatabaseClassName>().UseAsDataSource(_mapper).For<ViewModel>();
        }

In my Mapper Profile Class I have set it up like this:

    public class MapperProfile : Profile
    {
        public MapperProfile()
        {

            CreateMap<DatabaseClassName, ViewModel>().ReverseMap();
            //CreateMap(typeof(Source<>), typeof(Destination<>)).ReverseMap();
            
        }
    }

in my Startup class (ConfigureServices method) I have placed in:

            services.AddAutoMapper();

The error comes up as this:

    System.RuntimeType.GetPropertyImpl(string name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
    System.Type.GetProperty(string name, BindingFlags bindingAttr)
    System.Reflection.TypeExtensions.GetProperty(Type type, string name, BindingFlags bindingAttr)
    AutoQueryable.Helpers.SelectHelper.GetMemberExpression<TEntity>(Expression parent, SelectColumn column, IAutoQueryableProfile profile, bool isLambdaBody)
    AutoQueryable.Helpers.SelectHelper.InitType<TEntity>(IEnumerable<SelectColumn> columns, Expression node, IAutoQueryableProfile profile)
    AutoQueryable.Helpers.SelectHelper.GetSelector<TEntity, TResult>(ICollection<SelectColumn> selectColumns, IAutoQueryableProfile profile)
    AutoQueryable.Core.Models.AutoQueryHandler.GetDefaultSelectableQuery<T>(IQueryable<T> query)
    AutoQueryable.Core.Models.AutoQueryHandler.GetAutoQuery<T>(IQueryable<T> query)
    AutoQueryable.Core.Models.AutoQueryableContext.GetAutoQuery<T>(IQueryable<T> query)
    System.Dynamic.UpdateDelegates.UpdateAndExecute2<T0, T1, TRet>(CallSite site, T0 arg0, T1 arg1)
    AutoQueryable.AspNetCore.Filter.FilterAttributes.AutoQueryableFilter.OnActionExecuted(ActionExecutedContext context)
    Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
    Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
    Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
    Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
    Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
    Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
    Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
    Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

I was curious if anyone had any suggestions on fixing this.

**Comment by trenoncourt** [comment]
Hi @tomkurian01,

Seems to be a problem on ViewModel type introspection.

Can you paste the ViewModel type ?

Thx

**Comment by tomkurian01** [comment]
This was an error in the mapper configuration.
