### ISSUE TITLE
AutoQueryable with Mapster not all property project

### ISSUE THREAD

**Issue by kefengwei** [trenoncourt/AutoQueryable#74]
I'm using [Mapster](https://github.com/MapsterMapper/Mapster) as DTO utility. 
  In the [Wiki](https://github.com/trenoncourt/AutoQueryable#map-relations), i only see how to solve this problem for AutoMapper. 
 I have set `profile.ToListBeforeSelect = true`, but it still not work. So is there any other settings to help solve  this problem?

**Comment by kefengwei** [comment]
Sorry, there is no problem. I missed 

> This performs a ToList() using the AutoMapper mapping before using the select query parameters and selecting only the properties asked by the Querystring
@trenoncourt you can close.

**Comment by trenoncourt** [comment]
thanks ;)
